---

- import_tasks: selinux.yml
  when: ansible_selinux.status == "enabled"

- import_tasks: configure.yml

- import_tasks: install.yml

- name: Ensure haproxy_exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: haproxy_exporter
    enabled: true
    state: started
